CREATE TABLE IF NOT EXISTS data (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_data_status ON data (status);
